import mongoose from 'mongoose';

const medications = [
  {
    _id: new mongoose.Types.ObjectId(),
    medicationId: 'MED001',
    name: 'Paracetamol',
    description: 'Pain reliever and fever reducer',
    dosageForm: 'Tablet',
    manufacturer: 'Pharma Inc.',
    strength: '500mg',
    price: 5.0, // Price in USD
  },
  {
    _id: new mongoose.Types.ObjectId(),
    medicationId: 'MED002',
    name: 'Ibuprofen',
    description: 'Nonsteroidal anti-inflammatory drug (NSAID)',
    dosageForm: 'Tablet',
    manufacturer: 'HealthCorp',
    strength: '200mg',
    price: 8.0,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    medicationId: 'MED003',
    name: 'Amoxicillin',
    description:
      'Antibiotic used to treat a wide variety of bacterial infections',
    dosageForm: 'Capsule',
    manufacturer: 'BioPharm',
    strength: '250mg',
    price: 12.0,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    medicationId: 'MED004',
    name: 'Lisinopril',
    description: 'Used to treat high blood pressure (hypertension)',
    dosageForm: 'Tablet',
    manufacturer: 'MediLife',
    strength: '10mg',
    price: 15.0,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    medicationId: 'MED005',
    name: 'Metformin',
    description:
      'Helps control blood sugar levels for people with type 2 diabetes',
    dosageForm: 'Tablet',
    manufacturer: 'Wellness Pharma',
    strength: '500mg',
    price: 10.0,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    medicationId: 'MED006',
    name: 'Atorvastatin',
    description: 'Used to treat high cholesterol',
    dosageForm: 'Tablet',
    manufacturer: 'CardioMed',
    strength: '20mg',
    price: 20.0,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    medicationId: 'MED007',
    name: 'Ciprofloxacin',
    description: 'Antibiotic used to treat a variety of bacterial infections',
    dosageForm: 'Tablet',
    manufacturer: 'PharmaPlus',
    strength: '500mg',
    price: 18.0,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    medicationId: 'MED008',
    name: 'Amlodipine',
    description: 'Used to treat high blood pressure and angina',
    dosageForm: 'Tablet',
    manufacturer: 'HeartCare Ltd.',
    strength: '5mg',
    price: 7.0,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    medicationId: 'MED009',
    name: 'Omeprazole',
    description: 'Reduces stomach acid and treats GERD',
    dosageForm: 'Capsule',
    manufacturer: 'Digestive Health',
    strength: '20mg',
    price: 10.0,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    medicationId: 'MED010',
    name: 'Hydrochlorothiazide',
    description: 'Diuretic used to treat high blood pressure',
    dosageForm: 'Tablet',
    manufacturer: 'HydroPharm',
    strength: '25mg',
    price: 9.0,
  },
];

export default medications;
